
steps:

  - script: |
      pip install robotframework
      pip install pythonnet
    displayName: Install needed compoments from PyPi

  - task: NuGetCommand@2

  - task: VSBuild@1

  - script: |
      run_tests.cmd --exclude no_ci --xunit xunit.xml
    displayName: Executing tests

  - task: PublishTestResults@2
    inputs:
      testRunner: JUnit
      testResultsFiles: output/xunit.xml
  
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: output/log.html
      ArtifactType: Container
      TargetPath: ""
      ArtifactName: Test Logs

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: output/report.html
      ArtifactType: Container
      TargetPath: ""
      ArtifactName: Test Report